// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Card from "../Card.res.mjs";
import * as Bases from "../Bases.res.mjs";
import * as Rules from "../Rules.res.mjs";
import * as Boards from "../Boards.res.mjs";
import * as Common from "../Common.res.mjs";
import * as GameBase from "../GameBase.res.mjs";
import * as Core__Array from "@rescript/core/src/Core__Array.res.mjs";

var forEachSpace = Bases.BakersGame.makeForEachSpace(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, Rules.FreeCell.freeBaseRules, Rules.FreeCell.freeRules);

function initiateGame() {
  var shuffledDeck = Core__Array.toShuffled(Card.getDeck(0, false));
  var deckToDeal = {
    contents: shuffledDeck
  };
  return [
          shuffledDeck,
          {
            tableau: [
              Common.ArrayAux.popN(deckToDeal, 7),
              Common.ArrayAux.popN(deckToDeal, 7),
              Common.ArrayAux.popN(deckToDeal, 7),
              Common.ArrayAux.popN(deckToDeal, 7),
              Common.ArrayAux.popN(deckToDeal, 6),
              Common.ArrayAux.popN(deckToDeal, 6),
              Common.ArrayAux.popN(deckToDeal, 6),
              Common.ArrayAux.popN(deckToDeal, 6)
            ],
            foundations: [
              [],
              [],
              [],
              []
            ],
            foundations2: [],
            stock: [],
            waste: [],
            free: [
              undefined,
              undefined,
              undefined,
              undefined
            ]
          }
        ];
}

var Game = GameBase.Create({
      game_encode: Bases.BakersGame.game_encode,
      game_decode: Bases.BakersGame.game_decode,
      deck_encode: Bases.BakersGame.deck_encode,
      deck_decode: Bases.BakersGame.deck_decode,
      getSpace: Bases.BakersGame.getSpace,
      spaceToString: Bases.BakersGame.spaceToString,
      initiateGame: initiateGame,
      forEachSpace: forEachSpace,
      removeDragFromGame: Bases.BakersGame.removeDragFromGame,
      winCheck: Bases.BakersGame.winCheck,
      applyLiftToDragPile: Bases.BakersGame.applyLiftToDragPile,
      applyMoveToDragPile: Bases.BakersGame.applyMoveToDragPile,
      Board: Boards.FRT,
      AllCards: Bases.BakersGame.AllCards
    });

export {
  Game ,
}
/* Game Not a pure module */
