// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Packer from "./Packer.res.mjs";

var Klondike = Packer.Make({
      spec: {
        drop: "AltSuit",
        drag: "AltSuit",
        size: "AnySize",
        depot: {
          TAG: "SpecificDepot",
          _0: "RK"
        },
        foundation: "ByOne"
      }
    });

var BakersGame = Packer.Make({
      spec: {
        drop: "OneSuit",
        drag: "OneSuit",
        size: "FreeSize",
        depot: "AnyDepot",
        foundation: "ByOne"
      }
    });

var FreeCell = Packer.Make({
      spec: {
        drop: "AltSuit",
        drag: "AltSuit",
        size: "FreeSize",
        depot: "AnyDepot",
        foundation: "ByOne"
      }
    });

var SeahavenTowers = Packer.Make({
      spec: {
        drop: "OneSuit",
        drag: "OneSuit",
        size: "FreeSize",
        depot: {
          TAG: "SpecificDepot",
          _0: "RK"
        },
        foundation: "ByOne"
      }
    });

var Penguin = Packer.Make({
      spec: {
        drop: "CyclicOneSuit",
        drag: "CyclicOneSuit",
        size: "AnySize",
        depot: "AnyDepot",
        foundation: "ByOneCyclicOneSuit"
      }
    });

var AgnesSorel = Packer.Make({
      spec: {
        drop: "CyclicSameColor",
        drag: "CyclicOneSuit",
        size: "AnySize",
        depot: "AnyDepot",
        foundation: "ByOneCyclicOneSuit"
      }
    });

var Stalactite = Packer.Make({
      spec: {
        drop: "NoDrop",
        drag: "AnySuit",
        size: "JustOne",
        depot: "AnyDepot",
        foundation: "ByOneCyclicAnySuit"
      }
    });

var Spider = Packer.Make({
      spec: {
        drop: "AnySuit",
        drag: "OneSuit",
        size: "AnySize",
        depot: "AnyDepot",
        foundation: "ByAll"
      }
    });

var Scorpion = Packer.Make({
      spec: {
        drop: "OneSuit",
        drag: "AnySuit",
        size: "AnySize",
        depot: {
          TAG: "SpecificDepot",
          _0: "RK"
        },
        foundation: "ByAll"
      }
    });

var GermanPatience = Packer.Make({
      spec: {
        drop: "CyclicAnySuit",
        drag: "CyclicAnySuit",
        size: "AnySize",
        depot: "AnyDepot",
        foundation: "NoFoundation"
      }
    });

var EastHaven = Packer.Make({
      spec: {
        drop: "AltSuit",
        drag: "AltSuit",
        size: "AnySize",
        depot: "AnyDepot",
        foundation: "ByOne"
      }
    });

var GayGordons = Packer.Make({
      spec: {
        drop: "NoDrop",
        drag: "NoDrop",
        size: "JustOne",
        depot: "AnyDepot",
        foundation: "ByOne"
      }
    });

export {
  Klondike ,
  BakersGame ,
  FreeCell ,
  SeahavenTowers ,
  Penguin ,
  AgnesSorel ,
  Stalactite ,
  Spider ,
  Scorpion ,
  GermanPatience ,
  EastHaven ,
  GayGordons ,
}
/* Klondike Not a pure module */
