// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Card from "../Card.res.mjs";
import * as Bases from "../Bases.res.mjs";
import * as Boards from "../Boards.res.mjs";
import * as Common from "../Common.res.mjs";
import * as GameBase from "../GameBase.res.mjs";
import * as Core__Array from "@rescript/core/src/Core__Array.res.mjs";

var forEachSpace = Bases.Diplomat.makeForEachSpace(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined);

function initiateGame() {
  var shuffledDeck = Core__Array.toShuffled(Card.getDeck(0, false));
  var deckToDeal = {
    contents: shuffledDeck
  };
  deckToDeal.contents = Core__Array.filterMap(deckToDeal.contents, (function (v) {
          if (v.card.rank === "RA") {
            return ;
          } else {
            return v;
          }
        }));
  var tableau = [
    Common.ArrayAux.popN(deckToDeal, 6),
    Common.ArrayAux.popN(deckToDeal, 6),
    Common.ArrayAux.popN(deckToDeal, 6),
    Common.ArrayAux.popN(deckToDeal, 6),
    Common.ArrayAux.popN(deckToDeal, 6),
    Common.ArrayAux.popN(deckToDeal, 6),
    Common.ArrayAux.popN(deckToDeal, 6),
    Common.ArrayAux.popN(deckToDeal, 6)
  ];
  return [
          shuffledDeck,
          {
            tableau: tableau,
            foundations: [
              [{
                  card: {
                    suit: "Spades",
                    rank: "RA",
                    deck: 0
                  },
                  hidden: false
                }],
              [{
                  card: {
                    suit: "Hearts",
                    rank: "RA",
                    deck: 0
                  },
                  hidden: false
                }],
              [{
                  card: {
                    suit: "Diamonds",
                    rank: "RA",
                    deck: 0
                  },
                  hidden: false
                }],
              [{
                  card: {
                    suit: "Clubs",
                    rank: "RA",
                    deck: 0
                  },
                  hidden: false
                }]
            ],
            foundations2: [],
            stock: [],
            waste: [],
            free: []
          }
        ];
}

var Game = GameBase.Create({
      game_encode: Bases.Diplomat.game_encode,
      game_decode: Bases.Diplomat.game_decode,
      deck_encode: Bases.Diplomat.deck_encode,
      deck_decode: Bases.Diplomat.deck_decode,
      getSpace: Bases.Diplomat.getSpace,
      spaceToString: Bases.Diplomat.spaceToString,
      initiateGame: initiateGame,
      forEachSpace: forEachSpace,
      removeDragFromGame: Bases.Diplomat.removeDragFromGame,
      winCheck: Bases.Diplomat.winCheck,
      applyLiftToDragPile: Bases.Diplomat.applyLiftToDragPile,
      applyMoveToDragPile: Bases.Diplomat.applyMoveToDragPile,
      Board: Boards.FT,
      AllCards: Bases.Diplomat.AllCards
    });

export {
  Game ,
}
/* Game Not a pure module */
