// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Card from "../Card.res.mjs";
import * as Bases from "../Bases.res.mjs";
import * as Rules from "../Rules.res.mjs";
import * as Boards from "../Boards.res.mjs";
import * as Common from "../Common.res.mjs";
import * as GameBase from "../GameBase.res.mjs";
import * as Core__Array from "@rescript/core/src/Core__Array.res.mjs";
import * as GameCommons from "../GameCommons.res.mjs";

var forEachSpace = Bases.EastHaven.makeForEachSpace(undefined, undefined, undefined, undefined, undefined, undefined, Rules.DealAll.stockRules, undefined, undefined);

function initiateGame() {
  var shuffledDeck = Core__Array.toShuffled(Card.getDeck(0, true));
  var deckToDeal = {
    contents: shuffledDeck
  };
  return [
          shuffledDeck,
          {
            tableau: GameCommons.flipLastUp([
                  Common.ArrayAux.popN(deckToDeal, 3),
                  Common.ArrayAux.popN(deckToDeal, 3),
                  Common.ArrayAux.popN(deckToDeal, 3),
                  Common.ArrayAux.popN(deckToDeal, 3),
                  Common.ArrayAux.popN(deckToDeal, 3),
                  Common.ArrayAux.popN(deckToDeal, 3),
                  Common.ArrayAux.popN(deckToDeal, 3)
                ]),
            foundations: [
              [],
              [],
              [],
              []
            ],
            stock: [
              Common.ArrayAux.popN(deckToDeal, 3),
              Common.ArrayAux.popN(deckToDeal, 7),
              Common.ArrayAux.popN(deckToDeal, 7),
              Common.ArrayAux.popN(deckToDeal, 7),
              Common.ArrayAux.popN(deckToDeal, 7)
            ],
            waste: [],
            free: []
          }
        ];
}

var Game = GameBase.Create({
      game_encode: Bases.EastHaven.game_encode,
      game_decode: Bases.EastHaven.game_decode,
      deck_encode: Bases.EastHaven.deck_encode,
      deck_decode: Bases.EastHaven.deck_decode,
      getSpace: Bases.EastHaven.getSpace,
      spaceToString: Bases.EastHaven.spaceToString,
      initiateGame: initiateGame,
      forEachSpace: forEachSpace,
      removeDragFromGame: Bases.EastHaven.removeDragFromGame,
      winCheck: Bases.EastHaven.winCheck,
      applyLiftToDragPile: Bases.EastHaven.applyLiftToDragPile,
      applyMoveToDragPile: Bases.EastHaven.applyMoveToDragPile,
      Board: Boards.SFT,
      AllCards: Bases.EastHaven.AllCards
    });

export {
  Game ,
}
/* Game Not a pure module */
