// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Card from "../Card.res.mjs";
import * as Bases from "../Bases.res.mjs";
import * as Boards from "../Boards.res.mjs";
import * as Common from "../Common.res.mjs";
import * as GameBase from "../GameBase.res.mjs";
import * as Core__Array from "@rescript/core/src/Core__Array.res.mjs";

var forEachSpace = Bases.Fortress.makeForEachSpace(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined);

function initiateGame() {
  var shuffledDeck = Core__Array.toShuffled(Card.getDeck(0, false));
  var deckToDeal = {
    contents: shuffledDeck
  };
  var tableau = [
    Common.ArrayAux.popN(deckToDeal, 6),
    Common.ArrayAux.popN(deckToDeal, 6),
    Common.ArrayAux.popN(deckToDeal, 5),
    Common.ArrayAux.popN(deckToDeal, 5),
    Common.ArrayAux.popN(deckToDeal, 5),
    Common.ArrayAux.popN(deckToDeal, 5),
    Common.ArrayAux.popN(deckToDeal, 5),
    Common.ArrayAux.popN(deckToDeal, 5),
    Common.ArrayAux.popN(deckToDeal, 5),
    Common.ArrayAux.popN(deckToDeal, 5)
  ];
  return [
          shuffledDeck,
          {
            tableau: tableau,
            foundations: [
              [],
              [],
              [],
              []
            ],
            foundations2: [],
            stock: [],
            waste: [],
            free: []
          }
        ];
}

var Game = GameBase.Create({
      game_encode: Bases.Fortress.game_encode,
      game_decode: Bases.Fortress.game_decode,
      deck_encode: Bases.Fortress.deck_encode,
      deck_decode: Bases.Fortress.deck_decode,
      getSpace: Bases.Fortress.getSpace,
      spaceToString: Bases.Fortress.spaceToString,
      initiateGame: initiateGame,
      forEachSpace: forEachSpace,
      removeDragFromGame: Bases.Fortress.removeDragFromGame,
      winCheck: Bases.Fortress.winCheck,
      applyLiftToDragPile: Bases.Fortress.applyLiftToDragPile,
      applyMoveToDragPile: Bases.Fortress.applyMoveToDragPile,
      Board: Boards.FT,
      AllCards: Bases.Fortress.AllCards
    });

export {
  Game ,
}
/* Game Not a pure module */
