// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Card from "../Card.res.mjs";
import * as Decco from "@rescript-labs/decco/src/Decco.res.mjs";
import * as React from "react";
import * as Common from "../Common.res.mjs";
import * as Js_dict from "rescript/lib/es6/js_dict.js";
import * as Js_json from "rescript/lib/es6/js_json.js";
import * as Caml_obj from "rescript/lib/es6/caml_obj.js";
import * as GameBase from "../GameBase.res.mjs";
import * as Js_array from "rescript/lib/es6/js_array.js";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as Core__Array from "@rescript/core/src/Core__Array.res.mjs";
import * as GameCommons from "./GameCommons.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function space_encode(value) {
  if (typeof value !== "object") {
    if (value === "Waste") {
      return ["Waste"];
    } else {
      return ["Stock"];
    }
  }
  switch (value.TAG) {
    case "Card" :
        return [
                "Card",
                Card.card_encode(value._0)
              ];
    case "Foundation" :
        return [
                "Foundation",
                Decco.intToJson(value._0)
              ];
    case "Pile" :
        return [
                "Pile",
                Decco.intToJson(value._0)
              ];
    
  }
}

function space_decode(value) {
  var jsonArr = Js_json.classify(value);
  if (typeof jsonArr !== "object") {
    return Decco.error(undefined, "Not a variant", value);
  }
  if (jsonArr.TAG !== "JSONArray") {
    return Decco.error(undefined, "Not a variant", value);
  }
  var jsonArr$1 = jsonArr._0;
  if (jsonArr$1.length === 0) {
    return Decco.error(undefined, "Expected variant, found empty array", value);
  }
  var tagged = Js_array.map(Js_json.classify, jsonArr$1);
  var match = Belt_Array.getExn(tagged, 0);
  if (typeof match === "object" && match.TAG === "JSONString") {
    switch (match._0) {
      case "Card" :
          if (tagged.length !== 2) {
            return Decco.error(undefined, "Invalid number of arguments to variant constructor", value);
          }
          var v0 = Card.card_decode(Belt_Array.getExn(jsonArr$1, 1));
          if (v0.TAG === "Ok") {
            return {
                    TAG: "Ok",
                    _0: {
                      TAG: "Card",
                      _0: v0._0
                    }
                  };
          }
          var e = v0._0;
          return {
                  TAG: "Error",
                  _0: {
                    path: "[0]" + e.path,
                    message: e.message,
                    value: e.value
                  }
                };
      case "Foundation" :
          if (tagged.length !== 2) {
            return Decco.error(undefined, "Invalid number of arguments to variant constructor", value);
          }
          var v0$1 = Decco.intFromJson(Belt_Array.getExn(jsonArr$1, 1));
          if (v0$1.TAG === "Ok") {
            return {
                    TAG: "Ok",
                    _0: {
                      TAG: "Foundation",
                      _0: v0$1._0
                    }
                  };
          }
          var e$1 = v0$1._0;
          return {
                  TAG: "Error",
                  _0: {
                    path: "[0]" + e$1.path,
                    message: e$1.message,
                    value: e$1.value
                  }
                };
      case "Pile" :
          if (tagged.length !== 2) {
            return Decco.error(undefined, "Invalid number of arguments to variant constructor", value);
          }
          var v0$2 = Decco.intFromJson(Belt_Array.getExn(jsonArr$1, 1));
          if (v0$2.TAG === "Ok") {
            return {
                    TAG: "Ok",
                    _0: {
                      TAG: "Pile",
                      _0: v0$2._0
                    }
                  };
          }
          var e$2 = v0$2._0;
          return {
                  TAG: "Error",
                  _0: {
                    path: "[0]" + e$2.path,
                    message: e$2.message,
                    value: e$2.value
                  }
                };
      case "Stock" :
          if (tagged.length !== 1) {
            return Decco.error(undefined, "Invalid number of arguments to variant constructor", value);
          } else {
            return {
                    TAG: "Ok",
                    _0: "Stock"
                  };
          }
      case "Waste" :
          if (tagged.length !== 1) {
            return Decco.error(undefined, "Invalid number of arguments to variant constructor", value);
          } else {
            return {
                    TAG: "Ok",
                    _0: "Waste"
                  };
          }
      default:
        
    }
  }
  return Decco.error(undefined, "Invalid variant constructor", Belt_Array.getExn(jsonArr$1, 0));
}

function getSpace(element) {
  var d = space_decode(JSON.parse(element.id));
  if (d.TAG === "Ok") {
    return d._0;
  }
  
}

function spaceToString(space) {
  return JSON.stringify(space_encode(space));
}

function deck_encode(value) {
  return Decco.arrayToJson(Card.card_encode, value);
}

function deck_decode(value) {
  return Decco.arrayFromJson(Card.card_decode, value);
}

function game_encode(value) {
  return Js_dict.fromArray([
              [
                "piles",
                (function (extra) {
                      return Decco.arrayToJson((function (extra) {
                                    return Decco.arrayToJson(Card.card_encode, extra);
                                  }), extra);
                    })(value.piles)
              ],
              [
                "foundations",
                (function (extra) {
                      return Decco.arrayToJson((function (extra) {
                                    return Decco.arrayToJson(Card.card_encode, extra);
                                  }), extra);
                    })(value.foundations)
              ],
              [
                "stock",
                (function (extra) {
                      return Decco.arrayToJson(Card.card_encode, extra);
                    })(value.stock)
              ],
              [
                "waste",
                (function (extra) {
                      return Decco.arrayToJson(Card.card_encode, extra);
                    })(value.waste)
              ]
            ]);
}

function game_decode(value) {
  var dict = Js_json.classify(value);
  if (typeof dict !== "object") {
    return Decco.error(undefined, "Not an object", value);
  }
  if (dict.TAG !== "JSONObject") {
    return Decco.error(undefined, "Not an object", value);
  }
  var dict$1 = dict._0;
  var extra = Belt_Option.getWithDefault(Js_dict.get(dict$1, "piles"), null);
  var piles = Decco.arrayFromJson((function (extra) {
          return Decco.arrayFromJson(Card.card_decode, extra);
        }), extra);
  if (piles.TAG === "Ok") {
    var extra$1 = Belt_Option.getWithDefault(Js_dict.get(dict$1, "foundations"), null);
    var foundations = Decco.arrayFromJson((function (extra) {
            return Decco.arrayFromJson(Card.card_decode, extra);
          }), extra$1);
    if (foundations.TAG === "Ok") {
      var extra$2 = Belt_Option.getWithDefault(Js_dict.get(dict$1, "stock"), null);
      var stock = Decco.arrayFromJson(Card.card_decode, extra$2);
      if (stock.TAG === "Ok") {
        var extra$3 = Belt_Option.getWithDefault(Js_dict.get(dict$1, "waste"), null);
        var waste = Decco.arrayFromJson(Card.card_decode, extra$3);
        if (waste.TAG === "Ok") {
          return {
                  TAG: "Ok",
                  _0: Decco.unsafeAddFieldToObject("piles", piles._0, Decco.unsafeAddFieldToObject("foundations", foundations._0, Decco.unsafeAddFieldToObject("stock", stock._0, Decco.unsafeAddFieldToObject("waste", waste._0, {}))))
                };
        }
        var e = waste._0;
        return {
                TAG: "Error",
                _0: {
                  path: ".waste" + e.path,
                  message: e.message,
                  value: e.value
                }
              };
      }
      var e$1 = stock._0;
      return {
              TAG: "Error",
              _0: {
                path: ".stock" + e$1.path,
                message: e$1.message,
                value: e$1.value
              }
            };
    }
    var e$2 = foundations._0;
    return {
            TAG: "Error",
            _0: {
              path: ".foundations" + e$2.path,
              message: e$2.message,
              value: e$2.value
            }
          };
  }
  var e$3 = piles._0;
  return {
          TAG: "Error",
          _0: {
            path: ".piles" + e$3.path,
            message: e$3.message,
            value: e$3.value
          }
        };
}

function applyLiftToDragPile(dragPile, lift) {
  dragPile.forEach(function (v, j) {
        lift({
              TAG: "Card",
              _0: v
            }, j);
      });
}

function applyMoveToDragPile(dragPile, move) {
  dragPile.forEach(function (v, j) {
        move({
              TAG: "Card",
              _0: v
            }, 0, Math.imul(j, 20));
      });
}

function initiateGame() {
  var shuffledDeck = Core__Array.toShuffled(Card.getDeck(0));
  var deckToDeal = {
    contents: shuffledDeck
  };
  return [
          shuffledDeck,
          {
            piles: [
              Common.ArrayAux.popN(deckToDeal, 1),
              Common.ArrayAux.popN(deckToDeal, 2),
              Common.ArrayAux.popN(deckToDeal, 3),
              Common.ArrayAux.popN(deckToDeal, 4),
              Common.ArrayAux.popN(deckToDeal, 5),
              Common.ArrayAux.popN(deckToDeal, 6),
              Common.ArrayAux.popN(deckToDeal, 7)
            ],
            foundations: [
              [],
              [],
              [],
              []
            ],
            stock: deckToDeal.contents,
            waste: []
          }
        ];
}

function winCheck(game) {
  if (game.piles.every(function (pile) {
          return pile.length === 0;
        }) && game.stock.length === 0) {
    return game.waste.length === 0;
  } else {
    return false;
  }
}

function removeDragFromGame(game, dragPile) {
  var removeDragPile = function (x) {
    return x.filter(function (sCard) {
                return !dragPile.some(function (dCard) {
                            return Caml_obj.equal(sCard, dCard);
                          });
              });
  };
  return {
          piles: game.piles.map(removeDragPile),
          foundations: game.foundations.map(removeDragPile),
          stock: removeDragPile(game.stock),
          waste: removeDragPile(game.waste)
        };
}

function pileBaseRules(i) {
  return {
          droppedUpon: (function (game, dragPile) {
              var dragPileBase = dragPile[0];
              var noChildren = game.piles[i].length === 0;
              if (noChildren && dragPileBase.rank === "RK") {
                return {
                        piles: Common.ArrayAux.update(game.piles, i, (function (param) {
                                return dragPile;
                              })),
                        foundations: game.foundations,
                        stock: game.stock,
                        waste: game.waste
                      };
              }
              
            }),
          autoProgress: "Accept",
          onClick: (function (param) {
              
            })
        };
}

function pileRules(pile, card, i, j) {
  var isLast = j === (pile.length - 1 | 0);
  return {
          locationAdjustment: {
            x: 0,
            y: Math.imul(j, 20),
            z: j + 1 | 0
          },
          baseSpace: {
            TAG: "Pile",
            _0: i
          },
          dragPile: (function () {
              var dragPile = pile.slice(j);
              if (GameCommons.decAndAltValidation(dragPile)) {
                return dragPile;
              }
              
            }),
          autoProgress: (function () {
              if (isLast) {
                return {
                        TAG: "SendOrAccept",
                        _0: [card]
                      };
              } else {
                return "DoNothing";
              }
            }),
          droppedUpon: (function (game, dragPile) {
              var dragPileBase = dragPile[0];
              if (isLast && Card.rankIsAbove(card, dragPileBase) && Card.color(dragPileBase) !== Card.color(card)) {
                return {
                        piles: game.piles.map(function (stack) {
                              return Common.ArrayAux.insertAfter(stack, card, dragPile);
                            }),
                        foundations: game.foundations,
                        stock: game.stock,
                        waste: game.waste
                      };
              }
              
            }),
          onMove: (function (element) {
              if (isLast) {
                return Card.show(element);
              }
              
            }),
          onClick: (function (param) {
              
            })
        };
}

function foundationBaseRules(i) {
  return {
          droppedUpon: (function (game, dragPile) {
              var justOne = dragPile.length === 1;
              var dragPileBase = dragPile[0];
              var noChildren = game.foundations[i].length === 0;
              if (noChildren && justOne && dragPileBase.rank === "RA") {
                return {
                        piles: game.piles,
                        foundations: Common.ArrayAux.update(game.foundations, i, (function (param) {
                                return dragPile;
                              })),
                        stock: game.stock,
                        waste: game.waste
                      };
              }
              
            }),
          autoProgress: "Seek",
          onClick: (function (param) {
              
            })
        };
}

function foundationRules(game, card, i, j) {
  return {
          locationAdjustment: {
            x: 0,
            y: 0,
            z: j + 1 | 0
          },
          baseSpace: {
            TAG: "Foundation",
            _0: i
          },
          dragPile: (function () {
              if (j === (game.foundations.length - 1 | 0)) {
                return [card];
              }
              
            }),
          autoProgress: (function () {
              return "Seek";
            }),
          droppedUpon: (function (game, dragPile) {
              var justOne = dragPile.length === 1;
              var dragPileBase = dragPile[0];
              if (justOne && dragPileBase.suit === card.suit && Card.rankIsBelow(card, dragPileBase)) {
                return {
                        piles: game.piles,
                        foundations: game.foundations.map(function (stack) {
                              return Common.ArrayAux.insertAfter(stack, card, dragPile);
                            }),
                        stock: game.stock,
                        waste: game.waste
                      };
              }
              
            }),
          onMove: (function (param) {
              
            }),
          onClick: (function (param) {
              
            })
        };
}

function wasteRules(game, card, i) {
  return {
          locationAdjustment: {
            x: Math.imul(20, i),
            y: 0,
            z: i + 1 | 0
          },
          baseSpace: "Waste",
          dragPile: (function () {
              if (i === (game.waste.length - 1 | 0)) {
                return [card];
              }
              
            }),
          autoProgress: (function () {
              return "DoNothing";
            }),
          droppedUpon: (function (param, param$1) {
              
            }),
          onMove: (function (element) {
              Card.show(element);
            }),
          onClick: (function (param) {
              
            })
        };
}

function stockRules(i) {
  return {
          locationAdjustment: {
            x: 0,
            y: 0,
            z: i + 1 | 0
          },
          baseSpace: "Stock",
          dragPile: (function () {
              
            }),
          autoProgress: (function () {
              return "DoNothing";
            }),
          droppedUpon: (function (param, param$1) {
              
            }),
          onMove: (function (param) {
              
            }),
          onClick: (function (game) {
              return {
                      piles: game.piles,
                      foundations: game.foundations,
                      stock: game.stock.slice(0, game.stock.length - 1 | 0),
                      waste: game.waste.concat(game.stock.slice(game.stock.length - 1 | 0))
                    };
            })
        };
}

function stockBaseRules() {
  return {
          droppedUpon: (function (game, dragPile) {
              
            }),
          autoProgress: "DoNothing",
          onClick: (function (game) {
              return {
                      piles: game.piles,
                      foundations: game.foundations,
                      stock: game.waste.toReversed(),
                      waste: []
                    };
            })
        };
}

function getRule(game, match) {
  var result = {
    contents: undefined
  };
  game.piles.forEach(function (pile, i) {
        if (Caml_obj.equal({
                TAG: "Pile",
                _0: i
              }, match)) {
          result.contents = {
            TAG: "Static",
            _0: pileBaseRules(i)
          };
        }
        pile.forEach(function (card, j) {
              if (Caml_obj.equal({
                      TAG: "Card",
                      _0: card
                    }, match)) {
                result.contents = {
                  TAG: "Movable",
                  _0: pileRules(pile, card, i, j)
                };
                return ;
              }
              
            });
      });
  game.foundations.forEach(function (foundation, i) {
        if (Caml_obj.equal({
                TAG: "Foundation",
                _0: i
              }, match)) {
          result.contents = {
            TAG: "Static",
            _0: foundationBaseRules(i)
          };
        }
        foundation.forEach(function (card, j) {
              if (Caml_obj.equal({
                      TAG: "Card",
                      _0: card
                    }, match)) {
                result.contents = {
                  TAG: "Movable",
                  _0: foundationRules(game, card, i, j)
                };
                return ;
              }
              
            });
      });
  game.waste.forEach(function (card, i) {
        if (Caml_obj.equal({
                TAG: "Card",
                _0: card
              }, match)) {
          result.contents = {
            TAG: "Movable",
            _0: wasteRules(game, card, i)
          };
          return ;
        }
        
      });
  game.stock.forEach(function (card, i) {
        if (Caml_obj.equal({
                TAG: "Card",
                _0: card
              }, match)) {
          result.contents = {
            TAG: "Movable",
            _0: stockRules(i)
          };
          return ;
        }
        
      });
  if ("Stock" === match) {
    result.contents = {
      TAG: "Static",
      _0: stockBaseRules()
    };
  }
  return result.contents;
}

function Klondike$GameRules$Board(props) {
  var setRef = props.setRef;
  return JsxRuntime.jsxs(React.Fragment, {
              children: [
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("div", {
                              ref: Caml_option.some(setRef("Stock")),
                              className: " bg-black opacity-20 rounded w-14 h-20",
                              id: JSON.stringify(space_encode("Stock")),
                              onClick: props.onClick
                            }, JSON.stringify(space_encode("Stock"))),
                        JsxRuntime.jsx("div", {
                              ref: Caml_option.some(setRef("Waste")),
                              className: " w-14 h-20",
                              id: JSON.stringify(space_encode("Waste"))
                            }, JSON.stringify(space_encode("Waste")))
                      ],
                      className: "flex flex-row gap-3"
                    }),
                JsxRuntime.jsx("div", {
                      children: [
                          [],
                          [],
                          [],
                          []
                        ].map(function (param, i) {
                            return JsxRuntime.jsx("div", {
                                        ref: Caml_option.some(setRef({
                                                  TAG: "Foundation",
                                                  _0: i
                                                })),
                                        className: " bg-white opacity-10 rounded w-14 h-20",
                                        id: JSON.stringify(space_encode({
                                                  TAG: "Foundation",
                                                  _0: i
                                                }))
                                      }, JSON.stringify(space_encode({
                                                TAG: "Foundation",
                                                _0: i
                                              })));
                          }),
                      className: "flex flex-row gap-3 mt-5"
                    }),
                JsxRuntime.jsx("div", {
                      children: [
                          [],
                          [],
                          [],
                          [],
                          [],
                          [],
                          []
                        ].map(function (param, i) {
                            return JsxRuntime.jsx("div", {
                                        ref: Caml_option.some(setRef({
                                                  TAG: "Pile",
                                                  _0: i
                                                })),
                                        className: " bg-black opacity-20  rounded w-14 h-20",
                                        id: JSON.stringify(space_encode({
                                                  TAG: "Pile",
                                                  _0: i
                                                }))
                                      }, JSON.stringify(space_encode({
                                                TAG: "Pile",
                                                _0: i
                                              })));
                          }),
                      className: "flex flex-row gap-3 mt-5"
                    })
              ]
            });
}

var Board = {
  make: Klondike$GameRules$Board
};

function Klondike$GameRules$AllCards(props) {
  var onClick = props.onClick;
  var onMouseDown = props.onMouseDown;
  var setRef = props.setRef;
  return JsxRuntime.jsx(React.Fragment, {
              children: props.deck.map(function (card) {
                    return JsxRuntime.jsx(Card.Display.make, {
                                card: card,
                                id: JSON.stringify(space_encode({
                                          TAG: "Card",
                                          _0: card
                                        })),
                                cardRef: setRef({
                                      TAG: "Card",
                                      _0: card
                                    }),
                                onMouseDown: onMouseDown,
                                onClick: onClick,
                                hidden: true
                              }, JSON.stringify(space_encode({
                                        TAG: "Card",
                                        _0: card
                                      })));
                  })
            });
}

var AllCards = {
  make: Klondike$GameRules$AllCards
};

var GameRules = {
  game_encode: game_encode,
  game_decode: game_decode,
  deck_encode: deck_encode,
  deck_decode: deck_decode,
  getSpace: getSpace,
  spaceToString: spaceToString,
  initiateGame: initiateGame,
  getRule: getRule,
  removeDragFromGame: removeDragFromGame,
  winCheck: winCheck,
  applyLiftToDragPile: applyLiftToDragPile,
  applyMoveToDragPile: applyMoveToDragPile,
  Board: Board,
  AllCards: AllCards
};

var Game = GameBase.Create(GameRules);

export {
  GameRules ,
  Game ,
}
/* Game Not a pure module */
