// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Card from "../Card.res.mjs";
import * as React from "react";
import * as Common from "../Common.res.mjs";
import * as Packer from "./Packer.res.mjs";
import * as GameBase from "../GameBase.res.mjs";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as Core__Array from "@rescript/core/src/Core__Array.res.mjs";
import * as Core__Option from "@rescript/core/src/Core__Option.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function flipLastUp(piles) {
  return piles.map(function (pile) {
              return Common.ArrayAux.updateLast(pile, (function (v) {
                            return {
                                    card: v.card,
                                    hidden: false
                                  };
                          }));
            });
}

var SpiderBase = Packer.Make({
      spec: {
        drop: "AnySuit",
        drag: "OneSuit",
        size: "AnySize",
        depot: "AnyDepot",
        foundation: "ByAll"
      }
    });

var game_encode = SpiderBase.game_encode;

var game_decode = SpiderBase.game_decode;

var getSpace = SpiderBase.getSpace;

var spaceToString = SpiderBase.spaceToString;

var deck_encode = SpiderBase.deck_encode;

var deck_decode = SpiderBase.deck_decode;

var applyLiftToDragPile = SpiderBase.applyLiftToDragPile;

var applyMoveToDragPile = SpiderBase.applyMoveToDragPile;

var removeDragFromGame = SpiderBase.removeDragFromGame;

var AllCards = SpiderBase.AllCards;

function winCheck(game) {
  if (game.piles.every(function (pile) {
          return pile.length === 0;
        })) {
    return game.stock.every(function (stockGroup) {
                return stockGroup.length === 0;
              });
  } else {
    return false;
  }
}

function stockRules(_game, _card, i, j) {
  return {
          locationAdjustment: {
            x: Math.imul(i, 20),
            y: 0,
            z: (Math.imul(i, 10) + j | 0) + 1 | 0
          },
          baseSpace: "Stock",
          dragPile: (function () {
              
            }),
          autoProgress: (function () {
              return "DoNothing";
            }),
          droppedUpon: (function (_game, _dragPile) {
              
            }),
          onStateChange: (function (element) {
              Card.hide(element);
            }),
          onClick: (function (game) {
              return Core__Option.map(Common.ArrayAux.getLast(game.stock), (function (stockGroup) {
                            return {
                                    piles: flipLastUp(game.piles.map(function (pile, i) {
                                              return Core__Option.mapOr(stockGroup[i], pile, (function (v) {
                                                            return pile.concat([v]);
                                                          }));
                                            })),
                                    foundations: game.foundations,
                                    stock: game.stock.slice(0, game.stock.length - 1 | 0),
                                    waste: game.waste,
                                    free: game.free
                                  };
                          }));
            })
        };
}

var forEachSpace = SpiderBase.makeForEachSpace(undefined, undefined, undefined, undefined, undefined, undefined, stockRules, undefined, undefined);

function Spider$SpiderRules$StandardBoard(props) {
  var setRef = props.setRef;
  return JsxRuntime.jsxs(React.Fragment, {
              children: [
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("div", {
                              ref: Caml_option.some(setRef("Stock")),
                              className: " bg-white opacity-10  rounded w-14 h-20 mr-20"
                            }, spaceToString("Stock")),
                        JsxRuntime.jsx("div", {
                              children: [
                                  [],
                                  [],
                                  [],
                                  [],
                                  [],
                                  [],
                                  [],
                                  []
                                ].map(function (param, i) {
                                    return JsxRuntime.jsx("div", {
                                                ref: Caml_option.some(setRef({
                                                          TAG: "Foundation",
                                                          _0: i
                                                        })),
                                                className: " bg-white opacity-10  rounded w-14 h-20"
                                              }, spaceToString({
                                                    TAG: "Foundation",
                                                    _0: i
                                                  }));
                                  }),
                              className: "flex flex-row gap-3 ml-10"
                            })
                      ],
                      className: "flex flex-row"
                    }),
                JsxRuntime.jsx("div", {}),
                JsxRuntime.jsx("div", {
                      children: [
                          [],
                          [],
                          [],
                          [],
                          [],
                          [],
                          [],
                          [],
                          [],
                          []
                        ].map(function (param, i) {
                            return JsxRuntime.jsx("div", {
                                        ref: Caml_option.some(setRef({
                                                  TAG: "Pile",
                                                  _0: i
                                                })),
                                        className: " bg-black opacity-20   rounded w-14 h-20"
                                      }, spaceToString({
                                            TAG: "Pile",
                                            _0: i
                                          }));
                          }),
                      className: "flex flex-row gap-3 mt-5"
                    })
              ]
            });
}

var StandardBoard = {
  make: Spider$SpiderRules$StandardBoard
};

var SpiderRules_dropCheck = SpiderBase.dropCheck;

var SpiderRules_dragCheck = SpiderBase.dragCheck;

var SpiderRules_dragSizeCheck = SpiderBase.dragSizeCheck;

var SpiderRules_pileBaseCheck = SpiderBase.pileBaseCheck;

var SpiderRules_foundationBaseCheck = SpiderBase.foundationBaseCheck;

var SpiderRules_foundationCheck = SpiderBase.foundationCheck;

var SpiderRules_pileBaseRules = SpiderBase.pileBaseRules;

var SpiderRules_pileRules = SpiderBase.pileRules;

var SpiderRules_foundationBaseRules = SpiderBase.foundationBaseRules;

var SpiderRules_foundationRules = SpiderBase.foundationRules;

var SpiderRules_wasteRules = SpiderBase.wasteRules;

var SpiderRules_stockBaseRules = SpiderBase.stockBaseRules;

var SpiderRules_freeRules = SpiderBase.freeRules;

var SpiderRules_freeBaseRules = SpiderBase.freeBaseRules;

var SpiderRules_makeForEachSpace = SpiderBase.makeForEachSpace;

var SpiderRules = {
  game_encode: game_encode,
  game_decode: game_decode,
  getSpace: getSpace,
  spaceToString: spaceToString,
  deck_encode: deck_encode,
  deck_decode: deck_decode,
  dropCheck: SpiderRules_dropCheck,
  dragCheck: SpiderRules_dragCheck,
  dragSizeCheck: SpiderRules_dragSizeCheck,
  pileBaseCheck: SpiderRules_pileBaseCheck,
  foundationBaseCheck: SpiderRules_foundationBaseCheck,
  foundationCheck: SpiderRules_foundationCheck,
  applyLiftToDragPile: applyLiftToDragPile,
  applyMoveToDragPile: applyMoveToDragPile,
  removeDragFromGame: removeDragFromGame,
  pileBaseRules: SpiderRules_pileBaseRules,
  pileRules: SpiderRules_pileRules,
  foundationBaseRules: SpiderRules_foundationBaseRules,
  foundationRules: SpiderRules_foundationRules,
  wasteRules: SpiderRules_wasteRules,
  stockBaseRules: SpiderRules_stockBaseRules,
  freeRules: SpiderRules_freeRules,
  freeBaseRules: SpiderRules_freeBaseRules,
  makeForEachSpace: SpiderRules_makeForEachSpace,
  AllCards: AllCards,
  winCheck: winCheck,
  stockRules: stockRules,
  forEachSpace: forEachSpace,
  StandardBoard: StandardBoard
};

function initiateGame() {
  var shuffledDeck = Core__Array.toShuffled([].concat(Card.getOneSuitDeck(0, "Spades", true), Card.getOneSuitDeck(1, "Spades", true), Card.getOneSuitDeck(2, "Spades", true), Card.getOneSuitDeck(3, "Spades", true), Card.getOneSuitDeck(4, "Spades", true), Card.getOneSuitDeck(5, "Spades", true), Card.getOneSuitDeck(6, "Spades", true), Card.getOneSuitDeck(7, "Spades", true)));
  var deckToDeal = {
    contents: shuffledDeck
  };
  return [
          shuffledDeck,
          {
            piles: flipLastUp([
                  Common.ArrayAux.popN(deckToDeal, 6),
                  Common.ArrayAux.popN(deckToDeal, 6),
                  Common.ArrayAux.popN(deckToDeal, 6),
                  Common.ArrayAux.popN(deckToDeal, 6),
                  Common.ArrayAux.popN(deckToDeal, 5),
                  Common.ArrayAux.popN(deckToDeal, 5),
                  Common.ArrayAux.popN(deckToDeal, 5),
                  Common.ArrayAux.popN(deckToDeal, 5),
                  Common.ArrayAux.popN(deckToDeal, 5),
                  Common.ArrayAux.popN(deckToDeal, 5)
                ]),
            foundations: [
              [],
              [],
              [],
              [],
              [],
              [],
              [],
              []
            ],
            stock: [
              Common.ArrayAux.popN(deckToDeal, 10),
              Common.ArrayAux.popN(deckToDeal, 10),
              Common.ArrayAux.popN(deckToDeal, 10),
              Common.ArrayAux.popN(deckToDeal, 10),
              Common.ArrayAux.popN(deckToDeal, 10)
            ],
            waste: [],
            free: []
          }
        ];
}

var OneSuit = GameBase.Create({
      game_encode: game_encode,
      game_decode: game_decode,
      deck_encode: deck_encode,
      deck_decode: deck_decode,
      getSpace: getSpace,
      spaceToString: spaceToString,
      initiateGame: initiateGame,
      forEachSpace: forEachSpace,
      removeDragFromGame: removeDragFromGame,
      winCheck: winCheck,
      applyLiftToDragPile: applyLiftToDragPile,
      applyMoveToDragPile: applyMoveToDragPile,
      Board: StandardBoard,
      AllCards: AllCards
    });

function initiateGame$1() {
  var shuffledDeck = Core__Array.toShuffled([].concat(Card.getOneSuitDeck(0, "Spades", true), Card.getOneSuitDeck(1, "Spades", true), Card.getOneSuitDeck(2, "Spades", true), Card.getOneSuitDeck(3, "Spades", true), Card.getOneSuitDeck(4, "Hearts", true), Card.getOneSuitDeck(5, "Hearts", true), Card.getOneSuitDeck(6, "Hearts", true), Card.getOneSuitDeck(7, "Hearts", true)));
  var deckToDeal = {
    contents: shuffledDeck
  };
  return [
          shuffledDeck,
          {
            piles: flipLastUp([
                  Common.ArrayAux.popN(deckToDeal, 6),
                  Common.ArrayAux.popN(deckToDeal, 6),
                  Common.ArrayAux.popN(deckToDeal, 6),
                  Common.ArrayAux.popN(deckToDeal, 6),
                  Common.ArrayAux.popN(deckToDeal, 5),
                  Common.ArrayAux.popN(deckToDeal, 5),
                  Common.ArrayAux.popN(deckToDeal, 5),
                  Common.ArrayAux.popN(deckToDeal, 5),
                  Common.ArrayAux.popN(deckToDeal, 5),
                  Common.ArrayAux.popN(deckToDeal, 5)
                ]),
            foundations: [
              [],
              [],
              [],
              [],
              [],
              [],
              [],
              []
            ],
            stock: [
              Common.ArrayAux.popN(deckToDeal, 10),
              Common.ArrayAux.popN(deckToDeal, 10),
              Common.ArrayAux.popN(deckToDeal, 10),
              Common.ArrayAux.popN(deckToDeal, 10),
              Common.ArrayAux.popN(deckToDeal, 10)
            ],
            waste: [],
            free: []
          }
        ];
}

var TwoSuit = GameBase.Create({
      game_encode: game_encode,
      game_decode: game_decode,
      deck_encode: deck_encode,
      deck_decode: deck_decode,
      getSpace: getSpace,
      spaceToString: spaceToString,
      initiateGame: initiateGame$1,
      forEachSpace: forEachSpace,
      removeDragFromGame: removeDragFromGame,
      winCheck: winCheck,
      applyLiftToDragPile: applyLiftToDragPile,
      applyMoveToDragPile: applyMoveToDragPile,
      Board: StandardBoard,
      AllCards: AllCards
    });

function initiateGame$2() {
  var shuffledDeck = Core__Array.toShuffled([].concat(Card.getOneSuitDeck(0, "Spades", true), Card.getOneSuitDeck(1, "Spades", true), Card.getOneSuitDeck(2, "Clubs", true), Card.getOneSuitDeck(3, "Clubs", true), Card.getOneSuitDeck(4, "Hearts", true), Card.getOneSuitDeck(5, "Hearts", true), Card.getOneSuitDeck(6, "Diamonds", true), Card.getOneSuitDeck(7, "Diamonds", true)));
  var deckToDeal = {
    contents: shuffledDeck
  };
  return [
          shuffledDeck,
          {
            piles: flipLastUp([
                  Common.ArrayAux.popN(deckToDeal, 6),
                  Common.ArrayAux.popN(deckToDeal, 6),
                  Common.ArrayAux.popN(deckToDeal, 6),
                  Common.ArrayAux.popN(deckToDeal, 6),
                  Common.ArrayAux.popN(deckToDeal, 5),
                  Common.ArrayAux.popN(deckToDeal, 5),
                  Common.ArrayAux.popN(deckToDeal, 5),
                  Common.ArrayAux.popN(deckToDeal, 5),
                  Common.ArrayAux.popN(deckToDeal, 5),
                  Common.ArrayAux.popN(deckToDeal, 5)
                ]),
            foundations: [
              [],
              [],
              [],
              [],
              [],
              [],
              [],
              []
            ],
            stock: [
              Common.ArrayAux.popN(deckToDeal, 10),
              Common.ArrayAux.popN(deckToDeal, 10),
              Common.ArrayAux.popN(deckToDeal, 10),
              Common.ArrayAux.popN(deckToDeal, 10),
              Common.ArrayAux.popN(deckToDeal, 10)
            ],
            waste: [],
            free: []
          }
        ];
}

var FourSuit = GameBase.Create({
      game_encode: game_encode,
      game_decode: game_decode,
      deck_encode: deck_encode,
      deck_decode: deck_decode,
      getSpace: getSpace,
      spaceToString: spaceToString,
      initiateGame: initiateGame$2,
      forEachSpace: forEachSpace,
      removeDragFromGame: removeDragFromGame,
      winCheck: winCheck,
      applyLiftToDragPile: applyLiftToDragPile,
      applyMoveToDragPile: applyMoveToDragPile,
      Board: StandardBoard,
      AllCards: AllCards
    });

var spaceToString$1 = SpiderBase.spaceToString;

function initiateGame$3() {
  var shuffledDeck = Core__Array.toShuffled(Card.getDeck(0, false));
  var deckToDeal = {
    contents: shuffledDeck
  };
  return [
          shuffledDeck,
          {
            piles: [
              Common.ArrayAux.popN(deckToDeal, 8),
              Common.ArrayAux.popN(deckToDeal, 8),
              Common.ArrayAux.popN(deckToDeal, 8),
              Common.ArrayAux.popN(deckToDeal, 7),
              Common.ArrayAux.popN(deckToDeal, 6),
              Common.ArrayAux.popN(deckToDeal, 5),
              Common.ArrayAux.popN(deckToDeal, 4),
              Common.ArrayAux.popN(deckToDeal, 3),
              Common.ArrayAux.popN(deckToDeal, 2),
              Common.ArrayAux.popN(deckToDeal, 1)
            ],
            foundations: [
              [],
              [],
              [],
              []
            ],
            stock: [],
            waste: [],
            free: []
          }
        ];
}

function winCheck$1(game) {
  return game.piles.every(function (pile) {
              return pile.length === 0;
            });
}

var forEachSpace$1 = SpiderBase.makeForEachSpace(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined);

function Spider$SimpleSimon$Board(props) {
  var setRef = props.setRef;
  return JsxRuntime.jsxs(React.Fragment, {
              children: [
                JsxRuntime.jsx("div", {
                      children: [
                          [],
                          [],
                          [],
                          []
                        ].map(function (param, i) {
                            return JsxRuntime.jsx("div", {
                                        ref: Caml_option.some(setRef({
                                                  TAG: "Foundation",
                                                  _0: i
                                                })),
                                        className: " bg-white opacity-10 rounded w-14 h-20",
                                        id: spaceToString$1({
                                              TAG: "Foundation",
                                              _0: i
                                            })
                                      }, spaceToString$1({
                                            TAG: "Foundation",
                                            _0: i
                                          }));
                          }),
                      className: "flex flex-row gap-3 mt-5"
                    }),
                JsxRuntime.jsx("div", {
                      children: [
                          [],
                          [],
                          [],
                          [],
                          [],
                          [],
                          [],
                          [],
                          [],
                          []
                        ].map(function (param, i) {
                            return JsxRuntime.jsx("div", {
                                        ref: Caml_option.some(setRef({
                                                  TAG: "Pile",
                                                  _0: i
                                                })),
                                        className: " bg-black opacity-20  rounded w-14 h-20",
                                        id: spaceToString$1({
                                              TAG: "Pile",
                                              _0: i
                                            })
                                      }, spaceToString$1({
                                            TAG: "Pile",
                                            _0: i
                                          }));
                          }),
                      className: "flex flex-row gap-3 mt-5"
                    })
              ]
            });
}

var Board = {
  make: Spider$SimpleSimon$Board
};

var SimpleSimon = GameBase.Create({
      game_encode: SpiderBase.game_encode,
      game_decode: SpiderBase.game_decode,
      deck_encode: SpiderBase.deck_encode,
      deck_decode: SpiderBase.deck_decode,
      getSpace: SpiderBase.getSpace,
      spaceToString: spaceToString$1,
      initiateGame: initiateGame$3,
      forEachSpace: forEachSpace$1,
      removeDragFromGame: SpiderBase.removeDragFromGame,
      winCheck: winCheck$1,
      applyLiftToDragPile: SpiderBase.applyLiftToDragPile,
      applyMoveToDragPile: SpiderBase.applyMoveToDragPile,
      Board: Board,
      AllCards: SpiderBase.AllCards
    });

var ScorpionBase = Packer.Make({
      spec: {
        drop: "OneSuit",
        drag: "AnySuit",
        size: "AnySize",
        depot: "KingDepot",
        foundation: "ByAll"
      }
    });

var spaceToString$2 = ScorpionBase.spaceToString;

function initiateGame$4() {
  var shuffledDeck = Core__Array.toShuffled(Card.getDeck(0, true));
  var deckToDeal = {
    contents: shuffledDeck
  };
  return [
          shuffledDeck,
          {
            piles: flipLastUp([
                  Card.showAfter(Common.ArrayAux.popN(deckToDeal, 7), 3),
                  Card.showAfter(Common.ArrayAux.popN(deckToDeal, 7), 3),
                  Card.showAfter(Common.ArrayAux.popN(deckToDeal, 7), 3),
                  Card.showAfter(Common.ArrayAux.popN(deckToDeal, 7), 0),
                  Card.showAfter(Common.ArrayAux.popN(deckToDeal, 7), 0),
                  Card.showAfter(Common.ArrayAux.popN(deckToDeal, 7), 0),
                  Card.showAfter(Common.ArrayAux.popN(deckToDeal, 7), 0)
                ]),
            foundations: [
              [],
              [],
              [],
              []
            ],
            stock: [Common.ArrayAux.popN(deckToDeal, 3)],
            waste: [],
            free: []
          }
        ];
}

var forEachSpace$2 = ScorpionBase.makeForEachSpace(undefined, undefined, undefined, undefined, undefined, undefined, stockRules, undefined, undefined);

function Spider$Scorpion$Board(props) {
  var setRef = props.setRef;
  return JsxRuntime.jsxs(React.Fragment, {
              children: [
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("div", {
                              ref: Caml_option.some(setRef("Stock")),
                              className: " bg-white opacity-10  rounded w-14 h-20 mr-20"
                            }, spaceToString$2("Stock")),
                        JsxRuntime.jsx("div", {
                              children: [
                                  [],
                                  [],
                                  [],
                                  []
                                ].map(function (param, i) {
                                    return JsxRuntime.jsx("div", {
                                                ref: Caml_option.some(setRef({
                                                          TAG: "Foundation",
                                                          _0: i
                                                        })),
                                                className: " bg-white opacity-10  rounded w-14 h-20"
                                              }, spaceToString$2({
                                                    TAG: "Foundation",
                                                    _0: i
                                                  }));
                                  }),
                              className: "flex flex-row gap-3 ml-10"
                            })
                      ],
                      className: "flex flex-row"
                    }),
                JsxRuntime.jsx("div", {}),
                JsxRuntime.jsx("div", {
                      children: [
                          [],
                          [],
                          [],
                          [],
                          [],
                          [],
                          []
                        ].map(function (param, i) {
                            return JsxRuntime.jsx("div", {
                                        ref: Caml_option.some(setRef({
                                                  TAG: "Pile",
                                                  _0: i
                                                })),
                                        className: " bg-black opacity-20   rounded w-14 h-20"
                                      }, spaceToString$2({
                                            TAG: "Pile",
                                            _0: i
                                          }));
                          }),
                      className: "flex flex-row gap-3 mt-5"
                    })
              ]
            });
}

var Board$1 = {
  make: Spider$Scorpion$Board
};

var Scorpion = GameBase.Create({
      game_encode: ScorpionBase.game_encode,
      game_decode: ScorpionBase.game_decode,
      deck_encode: ScorpionBase.deck_encode,
      deck_decode: ScorpionBase.deck_decode,
      getSpace: ScorpionBase.getSpace,
      spaceToString: spaceToString$2,
      initiateGame: initiateGame$4,
      forEachSpace: forEachSpace$2,
      removeDragFromGame: ScorpionBase.removeDragFromGame,
      winCheck: winCheck,
      applyLiftToDragPile: ScorpionBase.applyLiftToDragPile,
      applyMoveToDragPile: ScorpionBase.applyMoveToDragPile,
      Board: Board$1,
      AllCards: ScorpionBase.AllCards
    });

export {
  flipLastUp ,
  SpiderBase ,
  SpiderRules ,
  OneSuit ,
  TwoSuit ,
  FourSuit ,
  SimpleSimon ,
  ScorpionBase ,
  Scorpion ,
}
/* SpiderBase Not a pure module */
