// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Packer from "./Packer.res.mjs";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as Core__Array from "@rescript/core/src/Core__Array.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function Boards$SWFT(props) {
  var initialGame = props.initialGame;
  var setRef = props.setRef;
  return JsxRuntime.jsxs(React.Fragment, {
              children: [
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("div", {
                              ref: Caml_option.some(setRef("Stock")),
                              className: " bg-black opacity-20 rounded w-14 h-20",
                              id: Packer.spaceToString("Stock")
                            }, Packer.spaceToString("Stock")),
                        JsxRuntime.jsx("div", {
                              ref: Caml_option.some(setRef("Waste")),
                              className: " w-14 h-20",
                              id: Packer.spaceToString("Waste")
                            }, Packer.spaceToString("Waste"))
                      ],
                      className: "flex flex-row gap-3"
                    }),
                JsxRuntime.jsx("div", {
                      children: Core__Array.make(initialGame.foundations.length, []).map(function (param, i) {
                            return JsxRuntime.jsx("div", {
                                        ref: Caml_option.some(setRef({
                                                  TAG: "Foundation",
                                                  _0: i
                                                })),
                                        className: " bg-white opacity-10 rounded w-14 h-20",
                                        id: Packer.spaceToString({
                                              TAG: "Foundation",
                                              _0: i
                                            })
                                      }, Packer.spaceToString({
                                            TAG: "Foundation",
                                            _0: i
                                          }));
                          }),
                      className: "flex flex-row gap-3 mt-5"
                    }),
                JsxRuntime.jsx("div", {
                      children: Core__Array.make(initialGame.tableau.length, []).map(function (param, i) {
                            return JsxRuntime.jsx("div", {
                                        ref: Caml_option.some(setRef({
                                                  TAG: "Tableau",
                                                  _0: i
                                                })),
                                        className: " bg-black opacity-20  rounded w-14 h-20",
                                        id: Packer.spaceToString({
                                              TAG: "Tableau",
                                              _0: i
                                            })
                                      }, Packer.spaceToString({
                                            TAG: "Tableau",
                                            _0: i
                                          }));
                          }),
                      className: "flex flex-row gap-3 mt-5"
                    })
              ]
            });
}

var SWFT = {
  make: Boards$SWFT
};

function Boards$FRT(props) {
  var initialGame = props.initialGame;
  var setRef = props.setRef;
  return JsxRuntime.jsxs(React.Fragment, {
              children: [
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("div", {
                              children: Core__Array.make(initialGame.free.length, []).map(function (param, i) {
                                    return JsxRuntime.jsx("div", {
                                                ref: Caml_option.some(setRef({
                                                          TAG: "Free",
                                                          _0: i
                                                        })),
                                                className: " bg-black opacity-20   rounded w-14 h-20"
                                              }, Packer.spaceToString({
                                                    TAG: "Free",
                                                    _0: i
                                                  }));
                                  }),
                              className: "flex flex-row gap-3"
                            }),
                        Core__Array.make((initialGame.tableau.length - initialGame.free.length | 0) - initialGame.foundations.length | 0, JsxRuntime.jsx("div", {
                                  className: "w-14 h-20"
                                })),
                        JsxRuntime.jsx("div", {
                              children: Core__Array.make(initialGame.foundations.length, []).map(function (param, i) {
                                    return JsxRuntime.jsx("div", {
                                                ref: Caml_option.some(setRef({
                                                          TAG: "Foundation",
                                                          _0: i
                                                        })),
                                                className: " bg-white opacity-10  rounded w-14 h-20"
                                              }, Packer.spaceToString({
                                                    TAG: "Foundation",
                                                    _0: i
                                                  }));
                                  }),
                              className: "flex flex-row gap-3"
                            })
                      ],
                      className: "flex flex-row gap-3"
                    }),
                JsxRuntime.jsx("div", {}),
                JsxRuntime.jsx("div", {
                      children: Core__Array.make(initialGame.tableau.length, []).map(function (param, i) {
                            return JsxRuntime.jsx("div", {
                                        ref: Caml_option.some(setRef({
                                                  TAG: "Tableau",
                                                  _0: i
                                                })),
                                        className: " bg-black opacity-20   rounded w-14 h-20"
                                      }, Packer.spaceToString({
                                            TAG: "Tableau",
                                            _0: i
                                          }));
                          }),
                      className: "flex flex-row gap-3 mt-5"
                    })
              ]
            });
}

var FRT = {
  make: Boards$FRT
};

function Boards$FRT2(props) {
  var initialGame = props.initialGame;
  var setRef = props.setRef;
  return JsxRuntime.jsxs(React.Fragment, {
              children: [
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("div", {
                              children: Core__Array.make(initialGame.free.length, []).map(function (param, i) {
                                    return JsxRuntime.jsx("div", {
                                                ref: Caml_option.some(setRef({
                                                          TAG: "Free",
                                                          _0: i
                                                        })),
                                                className: "   bg-black opacity-20  rounded w-14 h-20"
                                              }, Packer.spaceToString({
                                                    TAG: "Free",
                                                    _0: i
                                                  }));
                                  }),
                              className: "grid grid-cols-4 gap-3"
                            }),
                        Core__Array.make(2, JsxRuntime.jsx("div", {
                                  className: "w-14 h-20"
                                })),
                        JsxRuntime.jsx("div", {
                              children: Core__Array.make(initialGame.foundations.length, []).map(function (param, i) {
                                    return JsxRuntime.jsx("div", {
                                                ref: Caml_option.some(setRef({
                                                          TAG: "Foundation",
                                                          _0: i
                                                        })),
                                                className: "   bg-white opacity-10  rounded w-14 h-20"
                                              }, Packer.spaceToString({
                                                    TAG: "Foundation",
                                                    _0: i
                                                  }));
                                  }),
                              className: "grid grid-cols-4 gap-3 "
                            })
                      ],
                      className: "flex flex-row gap-3"
                    }),
                JsxRuntime.jsx("div", {}),
                JsxRuntime.jsx("div", {
                      children: Core__Array.make(initialGame.tableau.length, []).map(function (param, i) {
                            return JsxRuntime.jsx("div", {
                                        ref: Caml_option.some(setRef({
                                                  TAG: "Tableau",
                                                  _0: i
                                                })),
                                        className: " bg-black opacity-20  rounded w-14 h-20"
                                      }, Packer.spaceToString({
                                            TAG: "Tableau",
                                            _0: i
                                          }));
                          }),
                      className: "flex flex-row gap-3 mt-5"
                    })
              ]
            });
}

var FRT2 = {
  make: Boards$FRT2
};

function Boards$FRT3(props) {
  var initialGame = props.initialGame;
  var setRef = props.setRef;
  return JsxRuntime.jsx(React.Fragment, {
              children: JsxRuntime.jsxs("div", {
                    children: [
                      JsxRuntime.jsx("div", {
                            children: Core__Array.make(initialGame.foundations.length, []).map(function (param, i) {
                                  return JsxRuntime.jsx("div", {
                                              ref: Caml_option.some(setRef({
                                                        TAG: "Foundation",
                                                        _0: i
                                                      })),
                                              className: " bg-white opacity-10  rounded w-14 h-20"
                                            }, Packer.spaceToString({
                                                  TAG: "Foundation",
                                                  _0: i
                                                }));
                                }),
                            className: "flex flex-col gap-3 mr-6"
                          }),
                      JsxRuntime.jsxs("div", {
                            children: [
                              JsxRuntime.jsx("div", {
                                    children: JsxRuntime.jsx("div", {
                                          children: Core__Array.make(initialGame.free.length, []).map(function (param, i) {
                                                return JsxRuntime.jsx("div", {
                                                            ref: Caml_option.some(setRef({
                                                                      TAG: "Free",
                                                                      _0: i
                                                                    })),
                                                            className: " bg-black opacity-20   rounded w-14 h-20"
                                                          }, Packer.spaceToString({
                                                                TAG: "Free",
                                                                _0: i
                                                              }));
                                              }),
                                          className: "flex flex-row gap-3"
                                        }),
                                    className: "flex flex-row"
                                  }),
                              JsxRuntime.jsx("div", {}),
                              JsxRuntime.jsx("div", {
                                    children: Core__Array.make(initialGame.tableau.length, []).map(function (param, i) {
                                          return JsxRuntime.jsx("div", {
                                                      ref: Caml_option.some(setRef({
                                                                TAG: "Tableau",
                                                                _0: i
                                                              })),
                                                      className: " bg-black opacity-20   rounded w-14 h-20"
                                                    }, Packer.spaceToString({
                                                          TAG: "Tableau",
                                                          _0: i
                                                        }));
                                        }),
                                    className: "flex flex-row gap-3 mt-3"
                                  })
                            ]
                          })
                    ],
                    className: "flex flex-row"
                  })
            });
}

var FRT3 = {
  make: Boards$FRT3
};

function Boards$SFT(props) {
  var initialGame = props.initialGame;
  var setRef = props.setRef;
  return JsxRuntime.jsxs(React.Fragment, {
              children: [
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("div", {
                              ref: Caml_option.some(setRef("Stock")),
                              className: " bg-white opacity-10  rounded w-14 h-20 mr-20"
                            }, Packer.spaceToString("Stock")),
                        JsxRuntime.jsx("div", {
                              children: Core__Array.make(initialGame.foundations.length, []).map(function (param, i) {
                                    return JsxRuntime.jsx("div", {
                                                ref: Caml_option.some(setRef({
                                                          TAG: "Foundation",
                                                          _0: i
                                                        })),
                                                className: " bg-white opacity-10  rounded w-14 h-20"
                                              }, Packer.spaceToString({
                                                    TAG: "Foundation",
                                                    _0: i
                                                  }));
                                  }),
                              className: "flex flex-row gap-3 ml-10"
                            })
                      ],
                      className: "flex flex-row"
                    }),
                JsxRuntime.jsx("div", {}),
                JsxRuntime.jsx("div", {
                      children: Core__Array.make(initialGame.tableau.length, []).map(function (param, i) {
                            return JsxRuntime.jsx("div", {
                                        ref: Caml_option.some(setRef({
                                                  TAG: "Tableau",
                                                  _0: i
                                                })),
                                        className: " bg-black opacity-20   rounded w-14 h-20"
                                      }, Packer.spaceToString({
                                            TAG: "Tableau",
                                            _0: i
                                          }));
                          }),
                      className: "flex flex-row gap-3 mt-5"
                    })
              ]
            });
}

var SFT = {
  make: Boards$SFT
};

function Boards$SFTR(props) {
  var initialGame = props.initialGame;
  var setRef = props.setRef;
  return JsxRuntime.jsxs(React.Fragment, {
              children: [
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("div", {
                              ref: Caml_option.some(setRef("Stock")),
                              className: " bg-white opacity-10  rounded w-14 h-20 mr-20"
                            }, Packer.spaceToString("Stock")),
                        JsxRuntime.jsx("div", {
                              children: Core__Array.make(initialGame.foundations.length, []).map(function (param, i) {
                                    return JsxRuntime.jsx("div", {
                                                ref: Caml_option.some(setRef({
                                                          TAG: "Foundation",
                                                          _0: i
                                                        })),
                                                className: " bg-white opacity-10  rounded w-14 h-20"
                                              }, Packer.spaceToString({
                                                    TAG: "Foundation",
                                                    _0: i
                                                  }));
                                  }),
                              className: "flex flex-row gap-3 ml-10"
                            })
                      ],
                      className: "flex flex-row"
                    }),
                JsxRuntime.jsx("div", {
                      children: Core__Array.make(initialGame.free.length, []).map(function (param, i) {
                            return JsxRuntime.jsx("div", {
                                        ref: Caml_option.some(setRef({
                                                  TAG: "Free",
                                                  _0: i
                                                })),
                                        className: " bg-black opacity-20   rounded w-14 h-20"
                                      }, Packer.spaceToString({
                                            TAG: "Free",
                                            _0: i
                                          }));
                          }),
                      className: "flex flex-row gap-3 mt-5"
                    }),
                JsxRuntime.jsx("div", {
                      children: Core__Array.make(initialGame.tableau.length, []).map(function (param, i) {
                            return JsxRuntime.jsx("div", {
                                        ref: Caml_option.some(setRef({
                                                  TAG: "Tableau",
                                                  _0: i
                                                })),
                                        className: " bg-black opacity-20   rounded w-14 h-20"
                                      }, Packer.spaceToString({
                                            TAG: "Tableau",
                                            _0: i
                                          }));
                          }),
                      className: "flex flex-row gap-3 mt-5"
                    })
              ]
            });
}

var SFTR = {
  make: Boards$SFTR
};

function Boards$FT(props) {
  var initialGame = props.initialGame;
  var setRef = props.setRef;
  return JsxRuntime.jsxs(React.Fragment, {
              children: [
                JsxRuntime.jsx("div", {
                      children: Core__Array.make(initialGame.foundations.length, []).map(function (param, i) {
                            return JsxRuntime.jsx("div", {
                                        ref: Caml_option.some(setRef({
                                                  TAG: "Foundation",
                                                  _0: i
                                                })),
                                        className: " bg-white opacity-10 rounded w-14 h-20",
                                        id: Packer.spaceToString({
                                              TAG: "Foundation",
                                              _0: i
                                            })
                                      }, Packer.spaceToString({
                                            TAG: "Foundation",
                                            _0: i
                                          }));
                          }),
                      className: "flex flex-row gap-3 mt-5"
                    }),
                JsxRuntime.jsx("div", {
                      children: Core__Array.make(initialGame.tableau.length, []).map(function (param, i) {
                            return JsxRuntime.jsx("div", {
                                        ref: Caml_option.some(setRef({
                                                  TAG: "Tableau",
                                                  _0: i
                                                })),
                                        className: " bg-black opacity-20  rounded w-14 h-20",
                                        id: Packer.spaceToString({
                                              TAG: "Tableau",
                                              _0: i
                                            })
                                      }, Packer.spaceToString({
                                            TAG: "Tableau",
                                            _0: i
                                          }));
                          }),
                      className: "flex flex-row gap-3 mt-5"
                    })
              ]
            });
}

var FT = {
  make: Boards$FT
};

function Boards$ST(props) {
  var setRef = props.setRef;
  return JsxRuntime.jsxs(React.Fragment, {
              children: [
                JsxRuntime.jsx("div", {
                      children: JsxRuntime.jsx("div", {
                            ref: Caml_option.some(setRef("Stock")),
                            className: " bg-white opacity-10  rounded w-14 h-20 mr-20"
                          }, Packer.spaceToString("Stock")),
                      className: "flex flex-row"
                    }),
                JsxRuntime.jsx("div", {}),
                JsxRuntime.jsx("div", {
                      children: Core__Array.make(props.initialGame.tableau.length, []).map(function (param, i) {
                            return JsxRuntime.jsx("div", {
                                        ref: Caml_option.some(setRef({
                                                  TAG: "Tableau",
                                                  _0: i
                                                })),
                                        className: " bg-black opacity-20   rounded w-14 h-20"
                                      }, Packer.spaceToString({
                                            TAG: "Tableau",
                                            _0: i
                                          }));
                          }),
                      className: "flex flex-row gap-3 mt-5"
                    })
              ]
            });
}

var ST = {
  make: Boards$ST
};

export {
  SWFT ,
  FRT ,
  FRT2 ,
  FRT3 ,
  SFT ,
  SFTR ,
  FT ,
  ST ,
}
/* react Not a pure module */
