// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Caml_obj from "rescript/lib/es6/caml_obj.js";
import * as OtherJs from "./other.js";
import * as Core__Array from "@rescript/core/src/Core__Array.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";
import UseLocalStorageJs from "./useLocalStorage.js";

function numInterval(prim0, prim1, prim2) {
  return OtherJs.numInterval(prim0, prim1, prim2);
}

function removeLast(a) {
  return a.toReversed().slice(1).toReversed();
}

function getLast(a) {
  return a.toReversed()[0];
}

function update(a, i, f) {
  return a.map(function (el, j) {
              if (j === i) {
                return f(el);
              } else {
                return el;
              }
            });
}

function updateLast(a, f) {
  return a.map(function (el, j) {
              if (j === (a.length - 1 | 0)) {
                return f(el);
              } else {
                return el;
              }
            });
}

function insertAfter(arr, match, $$new) {
  return Core__Array.reduce(arr, [], (function (acc, c) {
                if (Caml_obj.equal(c, match)) {
                  return acc.concat([c].concat($$new));
                } else {
                  return acc.concat([c]);
                }
              }));
}

function forEach2(a, f) {
  a.forEach(function (el1, i) {
        el1.forEach(function (el2, j) {
              f(el1, el2, i, j);
            });
      });
}

function sliceBefore(arr, pred) {
  var revIndex = arr.toReversed().findIndex(pred);
  return arr.slice(0, (arr.length - 1 | 0) - revIndex | 0);
}

function popN(deck, n) {
  var result = deck.contents.slice(0, n);
  deck.contents = deck.contents.slice(n);
  return result;
}

var ArrayAux = {
  removeLast: removeLast,
  getLast: getLast,
  update: update,
  updateLast: updateLast,
  insertAfter: insertAfter,
  forEach2: forEach2,
  sliceBefore: sliceBefore,
  popN: popN
};

function Common$UtilBoard(props) {
  var restartGame = props.restartGame;
  var createNewGame = props.createNewGame;
  var undo = props.undo;
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("button", {
                      children: "Undo",
                      className: "bg-gray-200 rounded px-4 ",
                      onClick: (function (param) {
                          undo();
                        })
                    }),
                JsxRuntime.jsx("button", {
                      children: "New Game",
                      className: "bg-gray-200 rounded px-4 ",
                      onClick: (function (param) {
                          createNewGame();
                        })
                    }),
                JsxRuntime.jsx("button", {
                      children: "Restart Game",
                      className: "bg-gray-200 rounded px-4 ",
                      onClick: (function (param) {
                          restartGame();
                        })
                    }),
                JsxRuntime.jsx("div", {
                      children: props.isWin ? "You Won!" : null,
                      className: "px-4 font-black text-blue-600"
                    })
              ],
              className: "flex flex-row mb-5 mt-4 gap-2"
            });
}

var UtilBoard = {
  make: Common$UtilBoard
};

function useLocalStorage(prim0, prim1) {
  return UseLocalStorageJs(prim0, prim1);
}

export {
  numInterval ,
  ArrayAux ,
  UtilBoard ,
  useLocalStorage ,
}
/* ./other.js Not a pure module */
