// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Caml_obj from "rescript/lib/es6/caml_obj.js";
import * as OtherJs from "./other.js";
import * as Core__Array from "@rescript/core/src/Core__Array.res.mjs";

function numInterval(prim0, prim1, prim2) {
  return OtherJs.numInterval(prim0, prim1, prim2);
}

function removeLast(a) {
  return a.toReversed().slice(1).toReversed();
}

function getLast(a) {
  return a.toReversed()[0];
}

function update(a, i, f) {
  return a.map(function (el, j) {
              if (j === i) {
                return f(el);
              } else {
                return el;
              }
            });
}

function insertAfter(arr, match, $$new) {
  return Core__Array.reduce(arr, [], (function (acc, c) {
                if (Caml_obj.equal(c, match)) {
                  return acc.concat([c].concat($$new));
                } else {
                  return acc.concat([c]);
                }
              }));
}

function forEach2(a, f) {
  a.forEach(function (el1, i) {
        el1.forEach(function (el2, j) {
              f(el1, el2, i, j);
            });
      });
}

var ArrayAux = {
  removeLast: removeLast,
  getLast: getLast,
  update: update,
  insertAfter: insertAfter,
  forEach2: forEach2
};

export {
  numInterval ,
  ArrayAux ,
}
/* ./other.js Not a pure module */
